import * as vscode from 'vscode';

export function comment(editor: vscode.TextEditor | undefined, language: string, stenographyObject: any) {
    let ZERO_COLUMN = vscode.workspace.getConfiguration().get('stenography.autopilotSettings.zeroCol');

    const commentTypes:any = {
        'typescript': { start: '/*', end: '*/' },
        'tsx': { start: '/*', end: '*/' },
        'javascript': { start: '/*', end: '*/' },
        'html': { start: '<!--', end: '-->' },
        'css': { start: '/*', end: '*/' },
        'java': { start: '/*', end: '*/' },
        'c': { start: '/*', end: '*/' },
        'cpp': { start: '/*', end: '*/' },
        'csharp': { start: '/*', end: '*/' },
        'python': { start: "'''", end: "'''" },
        'php': { start: '/*', end: '*/' },
        'ruby': { start: "'''", end: "'''" },
    };
    
    if (!editor) {  
        vscode.window.showErrorMessage('Commit Comment :: No active editor');
        return;
    }

    if (!stenographyObject) {
        vscode.window.showErrorMessage('Commit Comment :: No stenography object');
        return;
    }

    if (!language) {
        vscode.window.showErrorMessage('Commit Comment :: No language');
        return;
    }

    const commentSeparator = commentTypes[language];
    

    const linesA: any[] = [];

    const columnPlacement = ZERO_COLUMN ? 1 : stenographyObject.startPosition.column - 1;

    editor?.edit(edit => {
        const lineAboveNewLine = new vscode.Position(
            stenographyObject.startPosition.row - 1,
            columnPlacement
        );
        linesA.push({ line: lineAboveNewLine, codeRes: stenographyObject.stenographyResult.pm });

        linesA.forEach((line:any) => {
            edit.insert(new vscode.Position(line.line.line, 0), '\n');
        });

    }).then(() => {
        editor?.edit(edit => {
            linesA.forEach((line:any, idx:number) => {
                edit.insert(new vscode.Position(line.line.line + idx, line.line.character), `${' '.repeat(line.line.character)}${commentSeparator.start}\n${' '.repeat(line.line.character)}${line.codeRes.replace(commentSeparator.end, '').replaceAll("\'", "\\'").split('\n').map((ln:string , idx:number) => {
                    if (idx === 0) {
                        return ln;
                    } 
                    return `${' '.repeat(line.line.character)}${ln}`;
                }).join('\n').trim()}\n${' '.repeat(line.line.character)}- generated by stenography autopilot [ 🚗👩‍✈️ ] \n${' '.repeat(line.line.character)}${commentSeparator.end}`);
            });
        });
    });
}